---
version: 2
updates:
# update github action once a month
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-actions-dependencies:
      update-types:
      - minor
      - patch
  commit-message:
    include: scope
    prefix: ci
# enable gemfile update once every week for security patches
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: weekly
  rebase-strategy: auto
  open-pull-requests-limit: 0
  commit-message:
    include: scope
    prefix: deps
