---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Install package and dependencies
        run: |
          sudo apt-get install ruby-full ruby-rspec
          sudo gem install climate_control
      - name: Run Tests
        run: export ACG_CONFIG="./test.json"; rspec spec/config_spec.rb
