---
name: Run Unit Tests

'on':
  - pull_request
  - push

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: latest
      - name: Run Tests
        run: export ACG_CONFIG="./test.json"; bundle exec rake spec
