name: "Schema updater"
on:
  schedule:
  - cron: "5 0 * * *"

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Fetch schema
        run: |
          ./sync_config.sh
          git add ./bin/schema.json ./lib/clowder-common-ruby/types.rb
          # If there are changes, bump version
          git diff-index --quiet HEAD -- || ./bin/bump_version
      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "chore(schema): update schema and bump version"
          commit-message: "chore(schema): update schema and bump version"
          author: Update-a-Bot <insights@redhat.com>
          committer: Update-a-Bot <insights@redhat.com>
          branch: "chore/schema-update"
          delete-branch: true
          add-paths: |
            bin/schema.json
            lib/clowder-common-ruby/types.rb
            lib/clowder-common-ruby/version.rb
