name: "Schema updater"
on:
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: latest
      - name: Fetch schema
        run: |
          cd bin
          wget https://raw.githubusercontent.com/RedHatInsights/clowder/master/controllers/cloud.redhat.com/config/schema.json -O schema.json
          ./json_schema_ruby -o ../lib/clowder-common-ruby/types.rb schema.json
          # Stage files to check if there are changes
          git add schema.json ../lib/clowder-common-ruby/types.rb
          # If there are changes, bump version
          git diff-index --quiet HEAD -- || ./bump_version
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "chore(schema): update schema and bump version"
          commit-message: "chore(schema): update schema and bump version"
          author: Update-a-Bot <insights@redhat.com>
          committer: Update-a-Bot <insights@redhat.com>
          branch: "chore/schema-update"
          delete-branch: true
          add-paths: |
            bin/schema.json
            lib/clowder-common-ruby/types.rb
            lib/clowder-common-ruby/version.rb
